### PR TITLE
Add ImageStream entry for fedora-26.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by LorbusChris** [comment]
what's blocking this?

**Comment by adelton** [comment]
We actually discussed it today -- I think the main blocker is that the `:fedora-26` tag / image is not really stable even in plain docker so making it easily available for OpenShift environments might bring wrong expectations too high. ;-)

**Comment by adelton** [comment]
Given the `:fedora-26` image seems to work rather fine at least on Fedora 25 hosts, could we get this merged?

**Comment by stlaz** [comment]
Yes, I completely forgot to push this. Thanks.

**Pull request merged**
