### PR TITLE
move `domainname` to a different directory rather than change its name so argv[0] remains the same

### PR DESCRIPTION
**Pull request by chesty**
https://github.com/freeipa/freeipa-container/issues/135#issuecomment-350522202

### CODE REVIEW

**Comment by stlaz** [comment]
I did not check the discussion #135 yet but that should not be a prerequisite to understand a commit message because commits are not necessarily connected to github.

Could you please improve the commit message to explain what you are actually doing? (Also, you used an email address not connected to your github account for the commit, although that may be just fine, up to you).

**Comment by adelton** [comment]
From `hostname --help`:

```
# hostname --help
Usage: hostname [-b] {hostname|-F file}         set host name (from file)
       hostname [-a|-A|-d|-f|-i|-I|-s|-y]       display formatted name
       hostname                                 display host name

       {yp,nis,}domainname {nisdomain|-F file}  set NIS domain name (from file)
       {yp,nis,}domainname                      display NIS domain name

       dnsdomainname                            display dns domain name

       hostname -V|--version|-h|--help          print info and exit

Program name:
       {yp,nis,}domainname=hostname -y
       dnsdomainname=hostname -d
```

The `/usr/bin/domainname` is a symlink to `hostname` and `hostname` seems to check its `argv[0]` and treat `domainname` as `hostname -y`.

I don't like the approach with `/usr/local/ipa`. I'd much rather just have code in the wrapper which calls `hostname -y` explicitly when invoked as `domainname`. Or we can have two different `-wrapper` calls.

**Comment by adelton** [comment]
The problem only happens when the container is started with `--cap-add SYS_ADMIN` which I believe we never do in our testing, that's why we did not hit the issue before.

**Comment by adelton** [comment]
I've now added (untested) commit https://github.com/freeipa/freeipa-container/pull/173/commits/058dcee695a0d47d154d86520eaa15a779463f68 to https://github.com/freeipa/freeipa-container/pull/173 to address the issue.

**Comment by adelton** [comment]
Moved to separate pull request https://github.com/freeipa/freeipa-container/pull/180 to make verification easier.

**Comment by adelton** [comment]
Let me close this pull request and focus on the https://github.com/freeipa/freeipa-container/pull/180 approach.

**Pull request closed without merging**
