### PR TITLE
Remove workaround configuring locale

### PR DESCRIPTION
**Pull request by stlaz**
This removes the workaround originally introduced for
https://bugzilla.redhat.com/show_bug.cgi?id=1343129 which seems to
be fixed now.

### CODE REVIEW

**Comment by adelton** [comment]
Does it fix that `ipactl` issue that you've been working on?

Shouldn't we change it in rawhide as well? And maybe 25 and 26 too?

**Comment by stlaz** [comment]
It did seem to fix the `ipactl` thing, I should hope it wasn't just random. We may change Fedoras 25 and 26 although FreeIPA requirements for UTF-8 do not apply there. Rawhide should definitely be changed.

**Comment by adelton** [comment]
Let's go bold and do the change on 25 onwards.

**Comment by stlaz** [comment]
Updated the changes.

**Comment by adelton** [comment]
LGTM.

**Pull request merged**
