### PR TITLE
[WIP] Use new fedora_container ipaplatform

### PR DESCRIPTION
**Pull request by tiran**
FreeIPA master and 4.8 branch have a new ipaplatform.fedora_container
platform definition. The new platform makes most patches to IPA code
obsolete.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by adelton** [comment]
The Travis CI seems to be failing with

```
("Unable to execute IPA upgrade: platform mismatch (expected 'fedora', current 'fedora_container')", 1)
The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information
```

**Comment by tiran** [comment]
Yes, https://github.com/freeipa/freeipa/pull/4992 takes care of the issue.

**Comment by tiran** [comment]
FreeIPA 4.8.9 will be released soon, probably today or tomorrow. I'm not available for two weeks starting on Monday. Could you please take care of this PR once 4.8.9 has reached Fedora stable?

**Comment by adelton** [comment]
Thanks. I've rebased on master and put the changes to Dockerfile.fedora-rawhide and Dockerfile.fedora-33. We will get the changes to Fedora 32 Dockerfile once the 4.9.8 bits are in the Fedora 32 repos.

**Pull request closed without merging**
