### PR TITLE
travis: test only existing Dockerfiles

### PR DESCRIPTION
**Pull request by stlaz**

### CODE REVIEW

**Comment by stlaz** [comment]
The `$( exec_cmds )` notation seem to have caused Travis to fail while using `|| :` so that the grep never fails (`|| :` actually got replaced by `|| =>`). Used backticks instead.

**Comment by adelton** [comment]
In https://github.com/freeipa/freeipa-container/pull/211 I spell out the list of Dockerfiles that we care about and I check that we only modify those. So https://github.com/freeipa/freeipa-container/pull/208 would likely fail with that but that does not matter -- we know what we are touching and removing.

**Comment by adelton** [comment]
I believe existing code in master addresses the need well.

**Comment by stlaz** [comment]
Yeah, I thought I closed this one. Thanks.

**Pull request closed without merging**
