### PR TITLE
Add a Fedora 27 container

### PR DESCRIPTION
**Pull request by stlaz**
This PR updates the Dockerfile for Fedora-rawhide and branches Fedora 27 image from it.

### CODE REVIEW

**Comment by adelton** [comment]
`which would the same but` -- verb missing in commit message.

**Comment by adelton** [comment]
Maybe you want to set `MAINTAINER` to someone else than me.

**Comment by adelton** [comment]
Untested, LGTM.

**Comment by stlaz** [comment]
Thanks, did not notice the missing verb. Assigning Tibor to test the PR.

**Comment by Tiboris** [comment]
The ipa-server-install works as expected. Thanks!

**Comment by adelton** [comment]
Do the test pass? Can we start using Fedora 27 containers?

**Comment by Tiboris** [comment]
Sorry for delay. There are SELinux denials but installation works. Thanks.

**Comment by adelton** [comment]
> Sorry for delay. There are SELinux denials but installation works. Thanks @stlaz

Please link to issues / bugzillas that were filed for the SELinux denials.

**Comment by Tiboris** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1517690

**Comment by adelton** [comment]
@Tiboris, fixed `container-selinux` for https://bugzilla.redhat.com/show_bug.cgi?id=1517690 is in Fedora koji -- can you retry with that and possibly ack this pull request?

**Comment by Tiboris** [comment]
I forgot to mention that tests are passing with container-selinux latest package in updates-testing.
We can definitely merge it.

**Pull request merged**
