### PR TITLE
Since domainname is symlink to hostname and hostname is smart based on argv[0], invoking domainname.orig would falsely set hostname.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by adelton** [comment]
The second commit of the original https://github.com/freeipa/freeipa-container/pull/173, to allow independent verification / merge.

**Comment by adelton** [comment]
Also, from https://github.com/freeipa/freeipa-container/pull/173#issuecomment-350661482:

But it might not be the best approach because apparently invoking domainname does not give exactly the same result as hostname -y, specifically when the domain/host name is provided / not being changed.

```
[root@www /]# hostname -y
hostname: Local domain name not set
[root@www /]# echo $?
1
[root@www /]# domainname
(none)
[root@www /]# echo $?
0
[root@www /]# 
```

Not sure if it causes some problem in FreeIPA use case though.

**Comment by adelton** [comment]
Untested.

**Comment by stlaz** [comment]
Tested and works.

I don't think the `domainname` behavior should have any effect on freeIPA. For the record I tried the `{yp,nis}domain` commands and it's actually these that behave the same as `hostname -y`.

ACK.

**Pull request merged**
